services:
  ntfy:
    image: binwiederhier/ntfy:v2.11.0
    container_name: ntfy_ntfy
    command:
      - serve
    environment:
      TZ: UTC
      NTFY_BASE_URL: ${NTFY_BASE_URL}
      NTFY_LISTEN_HTTP: :80
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      NTFY_WEB_PUSH_PUBLIC_KEY: ${NTFY_WEB_PUSH_PUBLIC_KEY}
      NTFY_WEB_PUSH_PRIVATE_KEY: ${NTFY_WEB_PUSH_PRIVATE_KEY}
      NTFY_WEB_PUSH_FILE: /var/lib/ntfy/webpush.db
      NTFY_WEB_PUSH_EMAIL_ADDRESS: ${NTFY_WEB_PUSH_EMAIL_ADDRESS}
      NTFY_ENABLE_SIGNUP: false
      NTFY_ENABLE_LOGIN: true
      NTFY_ENABLE_RESERVATIONS: false
      NTFY_UPSTREAM_BASE_URL: "https://ntfy.sh"
    volumes:
      - /docker/volumes/ntfy/data:/var/lib/ntfy
    ports:
      - "127.0.0.1:8008:80"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
