# .bashrc
# Set by Ansible

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# e.g. `10:58:20 [root@alma-4gb-nbg1-1:/dev/pts/0 ~ $`
export PS1="\n\[\e[0;36m\]\T \[\e[1;30m\][\[\e[1;34m\]\u@\H\[\e[1;30m\]:\[\e[0;37m\]${SSH_TTY:-o} \[\e[1;37m\]\w\[\e[0;37m\] \$ "

# Aliases
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
