nginx_proxy_cache_path: "/var/cache/nginx keys_zone=cache:32m"
nginx_vhosts:
  - server_name: "dev.{{ hostname }}"
    state: "present"
    template: "proxy.j2"
    proxy_port: 8000
  - server_name: "uptime.{{ hostname }}"
    state: "present"
    template: "proxy.j2"
    proxy_port: 8001
  - server_name: "grafana.{{ hostname }}"
    state: "present"
    template: "proxy.j2"
    proxy_port: 8002
  - server_name: "ente.{{ hostname }}"
    state: "present"
    template: "proxy.j2"
    proxy_port: 8003
  - server_name: "nextcloud.{{ hostname }}"
    state: "present"
    template: "proxy.j2"
    proxy_port: 8004
  - server_name: "ncadmin.{{ hostname }}"
    state: "present"
    template: "proxy.j2"
    proxy_port: 8005
    proxy_protocol: https
    trust_proxy_ssl: true
  - server_name: "overleaf.{{ hostname }}"
    state: "present"
    template: "proxy.j2"
    proxy_port: 8006
  - server_name: "joplin.{{ hostname }}"
    state: "present"
    template: "proxy.j2"
    proxy_port: 8007
nginx_service_state: started
nginx_service_enabled: true
