nginx_proxy_cache_path: "/var/cache/nginx keys_zone=cache:32m"
nginx_vhosts:
  - server_name: "dev.{{ hostname }}.com"
    state: "present"
    template: "proxy.j2"
    proxy_port: 8000
  - server_name: "uptime.{{ hostname }}.com"
    state: "present"
    template: "proxy.j2"
    proxy_port: 8001
  - server_name: "grafana.{{ hostname }}.com"
    state: "present"
    template: "proxy.j2"
    proxy_port: 8002
  - server_name: "ente.{{ hostname }}.com"
    state: "present"
    template: "proxy.j2"
    proxy_port: 8003
nginx_service_state: stopped
nginx_service_enabled: false
