os_auth_pw_max_age: 60
os_auth_pw_min_age: 7
os_auth_pw_warn_age: 7
os_auth_pw_remember: 24
os_auth_retry: 5
os_auth_lockout_time: 900
os_auth_timeout: 60
os_auth_pam_passwdqc_enable: false

sysctl_overwrite:
  # enable IPv4 traffic forwarding for docker
  net.ipv4.ip_forward: 1
