- name: Ensure chrony is installed
  ansible.builtin.package:
    name: chrony
    state: present

- name: Ensure chrony is enabled and running
  ansible.builtin.service:
    name: chronyd
    enabled: true
    state: started

- name: Configure chronyd
  ansible.builtin.template:
    src: chronyd.j2
    dest: /etc/sysconfig/chronyd
