- name: Aide hardening
  ansible.builtin.include_tasks: aide.yml

- name: Cron hardening
  ansible.builtin.include_tasks: cron.yml

- name: Fs hardening
  ansible.builtin.include_tasks: filesystem.yml

- name: Passwords hardening
  ansible.builtin.include_tasks: passwords.yml

- name: Ssh hardening
  ansible.builtin.include_tasks: ssh.yml

- name: Sudo hardening
  ansible.builtin.include_tasks: sudo.yml

- name: Configure System Cryptography Policy
  ansible.builtin.lineinfile:
    path: /etc/crypto-policies/config
    regexp: ^(?!#)(\S+)$
    line: "{{ cis_security_system_crypto_policy }}"
    create: true
    mode: "0644"

- name: Verify that Crypto Policy is Set (runtime)
  ansible.builtin.command: /usr/bin/update-crypto-policies \
    --set {{ cis_security_system_crypto_policy }}

- name: Modify the System Login Banner - Ensure Correct Banner
  ansible.builtin.copy:
    dest: "{{ item }}"
    content: "{{ cis_security_login_banner_text }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - /etc/issue
    - /etc/issue.net

- name: Ensure kernel module 'usb-storage' is disabled
  ansible.builtin.lineinfile:
    create: true
    dest: /etc/modprobe.d/usb-storage.conf
    regexp: install\s+usb-storage
    line: install usb-storage /bin/false
    owner: root
    group: root
    mode: "0644"
