- name: Ensure pam_pwquality is installed
  ansible.builtin.package:
    name: libpwquality
    state: present

- name: Ensure pwquality is configured securely
  ansible.builtin.lineinfile:
    create: true
    dest: /etc/security/pwquality.conf
    regexp: ^#?\s*{{ item.key }}
    line: "{{ item.key }} = {{ item.value }}"
  loop:
    - { key: "difok", value: 2 }
    - { key: "maxrepeat", value: 3 }
    - { key: "minclass", value: 4 }
    - { key: "minlen", value: 14 }
    - { key: "dictcheck", value: 1 }

- name: Ensure PAM Enforces Password Requirements for root user
  ansible.builtin.lineinfile:
    path: /etc/security/pwquality.conf
    line: enforce_for_root

- name: Ensure the Group Used by pam_wheel.so Module Exists on System and is Empty - Ensure sugroup Group Exists
  ansible.builtin.group:
    name: sugroup
    state: present

- name: Ensure the Group Used by pam_wheel.so Module Exists on System and is Empty - Ensure sugroup Group is Empty
  ansible.builtin.lineinfile:
    path: /etc/group
    regexp: ^(sugroup:[^:]+:[0-9]+:).*$
    line: \1
    backrefs: true

- name: Enforce Usage of pam_wheel with Group Parameter for su Authentication - Add the group to the /etc/pam.d/su file
  ansible.builtin.lineinfile:
    path: /etc/pam.d/su
    state: present
    regexp: ^[\s]*#[\s]*auth[\s]+required[\s]+pam_wheel\.so[\s]+use_uid group=$
    line: auth             required        pam_wheel.so use_uid group=sugroup
