- name: Ensure pam_pwquality is installed
  ansible.builtin.package:
    name: libpam-pwquality
    state: present

- name: Ensure pwquality is configured securely
  ansible.builtin.lineinfile:
    create: true
    dest: /etc/security/pwquality.conf
    regexp: ^#?\s*{{ item.key }}
    line: "{{ item.key }} = {{ item.value }}"
  when: '"pam" in ansible_facts.packages'
  loop:
    - { key: "difok", value: 2 }
    - { key: "maxrepeat", value: 3 }
    - { key: "minclass", value: 4 }
    - { key: "minlen", value: 14 }
