- name: Ensure SSHD uses strong KexAlgorithms
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    create: false
    regexp: (?i)^\s*KexAlgorithms\s+
    line: KexAlgorithms {{ cis_security_sshd_strong_kex }}
    state: present
    insertbefore: BOF
    validate: /usr/sbin/sshd -t -f %s

- name: Ensure SSHD uses strong MACs
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    create: false
    regexp: (?i)^\s*MACs\s+
    line: MACs {{ cis_security_sshd_strong_macs }}
    state: present
    insertbefore: BOF
    validate: /usr/sbin/sshd -t -f %s

- name: Configure SSH to use System Crypto Policy
  ansible.builtin.lineinfile:
    dest: /etc/sysconfig/sshd
    state: absent
    regexp: (?i)^\s*CRYPTO_POLICY.*$

- name: Find /etc/ssh/ file(s) matching ^.*_key$
  ansible.builtin.command: find -H /etc/ssh/ -maxdepth 1 -type f ! -group ssh_keys -regextype posix-extended -regex "^.*_key$"
  register: files_found
  changed_when: false
  failed_when: false
  check_mode: false

- name: Ensure group owner on /etc/ssh/ file(s) matching ^.*_key$
  ansible.builtin.file:
    path: "{{ item }}"
    group: ssh_keys
    state: file
  with_items:
    - "{{ files_found.stdout_lines }}"
