- name: Create joplin folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  loop:
    - /docker/compose/joplin
    - /docker/volumes/joplin

- name: Copy joplin folder
  ansible.builtin.copy:
    src: ./docker/joplin/
    dest: /docker/compose/joplin/
    mode: "0644"

- name: Shutdown service
  ansible.builtin.shell: |
    cd /docker/compose/joplin
    docker compose down

- name: Start service
  ansible.builtin.shell: |
    cd /docker/compose/joplin
    docker compose up -d
