- name: Create diun folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  loop:
    - /docker/compose/diun
    - /docker/volumes/diun

- name: Copy diun folder
  ansible.builtin.copy:
    src: ./docker/diun/
    dest: /docker/compose/diun/
    mode: "0644"

- name: Shutdown service
  ansible.builtin.shell: |
    cd /docker/compose/diun
    docker compose down

- name: Start service
  ansible.builtin.shell: |
    cd /docker/compose/diun
    docker compose up -d
