- name: Create ente folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  loop:
    - /docker/compose/ente
    - /docker/volumes/ente

- name: Copy ente folder
  ansible.builtin.copy:
    src: ./docker/ente/
    dest: /docker/compose/ente/
    mode: 0644

- name: Shutdown service
  ansible.builtin.shell: |
    cd /docker/compose/ente
    docker compose down

- name: Start service
  shell: |
    cd /docker/compose/ente
    docker compose up -d
