- name: Create grafana user for docker
  ansible.builtin.user:
    name: grafana
    state: present
    shell: /bin/bash
    create_home: false

- name: Create grafana folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  loop:
    - /docker/compose/grafana
    - /docker/volumes/grafana

- name: Copy grafana folder
  ansible.builtin.copy:
    src: ./docker/grafana/
    dest: /docker/compose/grafana/
    mode: "0644"

- name: Create docker volume directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: grafana
    group: grafana
  loop:
    - /docker/volumes/grafana/data
    - /docker/volumes/grafana/postgres_data
    - /docker/volumes/grafana/redis_data

- name: Set permissions for docker volumes
  ansible.builtin.command: chown -R grafana:grafana /docker/volumes/grafana

- name: Read grafana user
  ansible.builtin.command: id -u grafana
  register: grafana_user

- name: Set grafana user variable
  ansible.builtin.set_fact:
    grafana_user: "{{ grafana_user.stdout }}"

- name: Read grafana group
  ansible.builtin.command: id -g grafana
  register: grafana_group

- name: Set grafana group variable
  ansible.builtin.set_fact:
    grafana_group: "{{ grafana_group.stdout }}"

- name: Add user to docker .env file
  ansible.builtin.lineinfile:
    path: /docker/compose/grafana/.env
    line: "DOCKER_USER={{ grafana_user }}:{{ grafana_group }}"
    regexp: "^DOCKER_USER"
    create: false

- name: Shutdown service
  ansible.builtin.shell: |
    cd /docker/compose/grafana
    docker compose down

- name: Start service
  ansible.builtin.shell: |
    cd /docker/compose/grafana
    docker compose up -d
