- name: Create overleaf folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  loop:
    - /docker/compose/overleaf
    - /docker/volumes/overleaf

- name: Copy overleaf folder
  ansible.builtin.copy:
    src: ./docker/overleaf/
    dest: /docker/compose/overleaf/
    mode: "0644"

- name: Shutdown service
  ansible.builtin.shell: |
    cd /docker/compose/overleaf
    docker compose down

- name: Start service
  ansible.builtin.shell: |
    cd /docker/compose/overleaf
    docker compose up -d
