- name: Prepare docker directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: "0600"
    state: directory
  loop:
    - /docker
    - /docker/compose
    - /docker/volumes
