# copy priv and pub keys to nginx

- name: Create SSL directory
  ansible.builtin.file:
    path: /etc/ssl/{{ hostname }}/
    owner: root
    group: root
    mode: '0600'
    state: directory

- name: Copy SSL key
  ansible.builtin.copy:
    src: ./files/{{ hostname }}.priv
    dest: /etc/ssl/{{ hostname }}/
    mode: '0600'

- name: Copy SSL cert
  ansible.builtin.copy:
    src: ./files/{{ hostname }}.pub
    dest: /etc/ssl/{{ hostname }}/
    mode: '0600'

- name: Create /var/www/default directory
  ansible.builtin.file:
    path: /var/www/default
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Copy default favicon
  ansible.builtin.copy:
    src: ./files/favicon.ico
    dest: /var/www/default/
    mode: '0644'

- name: Start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Allow nginx to listen to 8000
  community.general.seport:
    ports: 8000
    proto: tcp
    setype: http_port_t
    state: absent

- name: Allow nginx can network connect
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
