services:
  museum:
    container_name: ente_museum
    image: ghcr.io/ente-io/server
    ports:
      - "127.0.0.1:8003:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Pass-in the config to connect to the DB and MinIO
      ENTE_CREDENTIALS_FILE: /credentials.yaml
    volumes:
      - /docker/volumes/ente/museum-logs:/var/logs
      - /docker/volumes/ente/museum-data:/data:ro
      - ./museum.yaml:/museum.yaml:ro
      - ./scripts/compose/credentials.yaml:/credentials.yaml:ro
    restart: always

  postgres:
    container_name: ente_postgres
    image: postgres:12
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: ente_db
    # Wait for postgres to be accept connections before starting museum.
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "ente_db", "-U", "pguser"]
      start_period: 40s
      start_interval: 1s
    volumes:
      - /docker/volumes/ente/postgres:/var/lib/postgresql/data
    restart: always
