- name: Setup new server with Docker & Nginx

  hosts: all

  become: true

  gather_facts: true

  vars_files:
    - vars/private.yml
    - vars/common.yml
    - vars/timezone.yml
    - vars/dnfautomatic.yml
    - vars/nginx.yml
    - vars/firewall.yml
    - vars/fail2ban.yml
    - vars/ssh-hardening.yml
    - vars/os-hardening.yml

  roles:
    - role: devsec.hardening.os_hardening
    - role: devsec.hardening.ssh_hardening
    - role: cis_hardening

  tasks:
    - import_tasks: tasks/openscap.yml
