- name: Setup new server with Docker & Nginx

  hosts: all

  become: true

  gather_facts: yes

  vars_files:
    - vars/common.yml
    - vars/timezone.yml
    - vars/dnfautomatic.yml
    - vars/nginx.yml
    - vars/firewall.yml
    - vars/fail2ban.yml
    - vars/os-hardening.yml

  roles:
    - role: cis_security
    # - role: robertdebock.fail2ban
    # - role: geerlingguy.nginx
    # - role: devsec.hardening.ssh_hardening
    # - role: devsec.hardening.os_hardening

  tasks:
    - import_tasks: tasks/openscap.yml
    # - import_tasks: tasks/root-qol.yml
    # - import_tasks: tasks/docker-grafana.yml
    # - import_tasks: tasks/docker-fail2ban-exporter.yml
    # - import_tasks: tasks/start-nginx.yml
