- name: Setup new server with Docker & Nginx

  hosts: all

  become: true

  gather_facts: yes

  vars_files:
    - vars/common.yml
    - vars/timezone.yml
    - vars/dnfautomatic.yml
    - vars/nginx.yml
    - vars/firewall.yml

  roles:
    - role: geerlingguy.nginx

  tasks:
    # - import_tasks: tasks/root-qol.yml
    - import_tasks: tasks/docker-grafana.yml
    - import_tasks: tasks/start-nginx.yml
