- name: Setup new server with Docker & Nginx

  hosts: all

  become: true

  gather_facts: yes

  vars_files:
    - vars/common.yml
    - vars/timezone.yml
    - vars/dnfautomatic.yml
    - vars/nginx.yml

  roles:
    - role: geerlingguy.nginx
    - role: devsec.hardening.nginx_hardening
      vars:
        # small changes from hardening default for more compatability with shit
        nginx_add_header:  # changes: I removed CSP because it broke uptime-kuma
          # avoid clickjacking
          - X-Frame-Options SAMEORIGIN
          # disable content-type sniffing
          - X-Content-Type-Options nosniff
          # XSS filter
          - X-XSS-Protection "1; mode=block"
          - Strict-Transport-Security max-age=15768000
        nginx_client_max_body_size: "10k"
        nginx_large_client_header_buffers: "4 2k"

  tasks:
    - import_tasks: tasks/docker-helloworld.yml
    - import_tasks: tasks/docker-uptime-kuma.yml
    - import_tasks: tasks/start-nginx.yml
