- name: Setup new server with Docker & Nginx

  hosts: all

  become: true

  gather_facts: yes

  vars_files:
    - vars/common.yml
    - vars/timezone.yml
    - vars/dnfautomatic.yml
    - vars/nginx.yml
    - vars/firewall.yml
    - vars/fail2ban.yml
    - vars/os-hardening.yml

  roles:
    - role: geerlingguy.nginx

  tasks:
    - import_tasks: tasks/install-standard-apps.yml
    - import_tasks: tasks/docker-ente.yml
    - import_tasks: tasks/start-nginx.yml
