- name: Setup new server with Docker & Nginx

  hosts: all

  become: true

  gather_facts: yes

  vars_files:
    - vars/common.yml
    - vars/timezone.yml

  roles:
    - role: geerlingguy.git
    - role: geerlingguy.docker
    - role: geerlingguy.repo-epel

  tasks:
    - import_tasks: tasks/utils.yml
    - import_tasks: tasks/install-btop.yml
