- name: Setup new server with Docker & Nginx

  hosts: all

  become: true

  gather_facts: true

  vars_files:
    - vars/private.yml
    - vars/common.yml
    - vars/timezone.yml
    - vars/dnfautomatic.yml
    - vars/nginx.yml
    - vars/firewall.yml
    - vars/fail2ban.yml
    - vars/os-hardening.yml

  roles:
    - role: user_qol
    - role: geerlingguy.firewall
    - role: geerlingguy.git
    - role: geerlingguy.docker
    - role: geerlingguy.repo-epel
    - role: geerlingguy.nginx
    - role: devsec.hardening.os_hardening
    - role: devsec.hardening.ssh_hardening
    - role: devsec.hardening.nginx_hardening
      vars:
        # small changes from hardening default for more compatability with shit
        nginx_add_header:  # changes: I removed CSP because it broke uptime-kuma
          # avoid clickjacking
          - X-Frame-Options SAMEORIGIN
          # disable content-type sniffing
          - X-Content-Type-Options nosniff
          # XSS filter
          - X-XSS-Protection "1; mode=block"
          - Strict-Transport-Security max-age=15768000
        nginx_client_max_body_size: "10k"
        nginx_large_client_header_buffers: "4 2k"
        # slightly higher (5 to 10) connection limit
        nginx_limit_conn: default 10
    - role: robertdebock.fail2ban
    - role: cis_security

  tasks:
    - import_tasks: tasks/utils.yml
    - import_tasks: tasks/install-standard-apps.yml
    - import_tasks: tasks/prepare-docker.yml
    - import_tasks: tasks/docker-helloworld.yml
    - import_tasks: tasks/docker-uptime-kuma.yml
    - import_tasks: tasks/docker-grafana.yml
    - import_tasks: tasks/docker-ente.yml
    - import_tasks: tasks/start-nginx.yml
    - import_tasks: tasks/dnf-automatic.yml
    - import_tasks: tasks/openscap.yml
