global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["127.0.0.1:9090"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["grafana_node_exporter:9100"]
  - job_name: "fail2ban_exporter"
    static_configs:
      - targets: ["fail2ban_exporter:9100"]
  - job_name: "ente"
    static_configs:
      - targets: ["ente_prom_nginx:80"]
  - job_name: "overleaf"
    static_configs:
      - targets: ["overleaf_prom_nginx:80"]
  - job_name: "uptimekuma"
    static_configs:
      - targets: ["uptimekuma_prom_nginx:80"]
