- name: Ensure SSHD uses strong KexAlgorithms
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    create: false
    regexp: (?i)^\s*KexAlgorithms\s+
    line: KexAlgorithms {{ cis_security_sshd_strong_kex }}
    state: present
    insertbefore: BOF
    validate: /usr/sbin/sshd -t -f %s

- name: Ensure SSHD uses strong MACs
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    create: false
    regexp: (?i)^\s*MACs\s+
    line: MACs {{ cis_security_sshd_strong_macs }}
    state: present
    insertbefore: BOF
    validate: /usr/sbin/sshd -t -f %s
